pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [ikhoon]
      label:
        add: [dependencies]
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=test
      - body~=labels:.*semver-patch
    actions:
      merge:
        method: squash
